/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PayObligationIdRouteImport } from './routes/pay.$obligationId'
import { Route as AdminCollectionsIndexRouteImport } from './routes/admin/collections/index'
import { Route as AdminCollectionsCollectionIdRouteImport } from './routes/admin/collections/$collectionId'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayObligationIdRoute = PayObligationIdRouteImport.update({
  id: '/pay/$obligationId',
  path: '/pay/$obligationId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsIndexRoute = AdminCollectionsIndexRouteImport.update({
  id: '/admin/collections/',
  path: '/admin/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsCollectionIdRoute =
  AdminCollectionsCollectionIdRouteImport.update({
    id: '/admin/collections/$collectionId',
    path: '/admin/collections/$collectionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/admin/payments/',
  path: '/admin/payments/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pay/$obligationId': typeof PayObligationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pay/$obligationId': typeof PayObligationIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections': typeof AdminCollectionsIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/pay/$obligationId': typeof PayObligationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$collectionId': typeof AdminCollectionsCollectionIdRoute
  '/admin/collections/': typeof AdminCollectionsIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pay/$obligationId'
    | '/admin/'
    | '/admin/collections/$collectionId'
    | '/admin/collections/'
    | '/admin/payments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/pay/$obligationId'
    | '/admin'
    | '/admin/collections/$collectionId'
    | '/admin/collections'
    | '/admin/payments'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pay/$obligationId'
    | '/admin/'
    | '/admin/collections/$collectionId'
    | '/admin/collections/'
    | '/admin/payments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PayObligationIdRoute: typeof PayObligationIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsCollectionIdRoute: typeof AdminCollectionsCollectionIdRoute
  AdminCollectionsIndexRoute: typeof AdminCollectionsIndexRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$obligationId': {
      id: '/pay/$obligationId'
      path: '/pay/$obligationId'
      fullPath: '/pay/$obligationId'
      preLoaderRoute: typeof PayObligationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/': {
      id: '/admin/collections/'
      path: '/admin/collections'
      fullPath: '/admin/collections/'
      preLoaderRoute: typeof AdminCollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$collectionId': {
      id: '/admin/collections/$collectionId'
      path: '/admin/collections/$collectionId'
      fullPath: '/admin/collections/$collectionId'
      preLoaderRoute: typeof AdminCollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/admin/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PayObligationIdRoute: PayObligationIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsCollectionIdRoute: AdminCollectionsCollectionIdRoute,
  AdminCollectionsIndexRoute: AdminCollectionsIndexRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
